version: 1
update_configs:
  # Automatically merge security updates into master
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    target_branch: "trunk"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "security:patch"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "trunk"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "security:patch"
